module.exports = {
    url: 'http://localhost:3000/#/',
    elements: {
        versionNumber: 'h6',
        titleText: 'h1[class="titleBar"]',
        welcomeScreen: '#welcomeScreen',
        menuButton: '.bm-burger-button',
        homeOption: 'p[name="homeOption"]',
        enterOption: 'p[name="enterOption"]',
        modifyOption: 'p[name="modifyOption"]',
        cancelOption: 'p[name="cancelOption"]',
        widInput: 'input[name="widInput"]',
        hdrInput: 'input[name="hdrInput"]',
        mkeInput: 'input[name="mkeInput"]',
        oaiInput: 'input[name="oriInput"]',
        namInput: 'input[name="namInput"]',
        sexInput: 'select[name="sexInput"]',
        racInput: 'select[name="racInput"]',
        hgtInput: 'input[name="hgtInput"]',
        wgtInput: 'input[name="wgtInput"]',
        haiInput: 'input[name="haiInput"]',
        offInput: 'input[name="offInput"]',
        dowInput: 'input[name="dowInput"]',
        licenseInput: 'input[name="olnInput"]',
        dlStateInput: 'input[name="olsInput"]',
        dlDateInput: 'input[name="oldInput"]',
        licPlateInput: 'input[name="licInput"]',
        licStateInput: 'input[name="lisInput"]',
        licDateInput: 'input[name="lidInput"]',
        submitButton: '#saveBtn',
        clearButton: '#clearBtn',
        queryBody: 'span[name="queryBody"]',
        errorMessage: 'li[class="errorMessage"]',
        reasonInput: 'input[name="resInput"]',
        cancelDateInput: 'input[name="datInput"]',

    }
}