module.exports = (pageObject, formInfo) => {
    pageObject
        .clearValue('@hdrInput')
        .setValue('@hdrInput', formInfo.header)
        .clearValue('@mkeInput')
        .setValue('@mkeInput', formInfo.mke)
        .clearValue('@oaiInput')
        .setValue('@oaiInput', formInfo.oai)
        .clearValue('@namInput')
        .setValue('@namInput', formInfo.name)
        .clearValue('@sexInput')
        .click(`option[value="${formInfo.sex}"]`)
    pageObject
    .clearValue('@racInput')
        .click(`option[value="${formInfo.race}"]`)
        .clearValue('@hgtInput')
        .setValue('@hgtInput', formInfo.height)
        .clearValue('@wgtInput')
        .setValue('@wgtInput', formInfo.weight)
        .clearValue('@haiInput')
        .setValue('@haiInput', formInfo.hair)
        .clearValue('@offInput')
        .setValue('@offInput', formInfo.offense)
        .clearValue('@dowInput')
        .setValue('@dowInput', formInfo.dow)
        .clearValue('@licenseInput')
        .setValue('@licenseInput', formInfo.license)
        .clearValue('@dlStateInput')
        .setValue('@dlStateInput', formInfo.dlState)
        .clearValue('@dlDateInput')
        .setValue('@dlDateInput', formInfo.dlDate)
        .clearValue('@licPlateInput')
        .setValue('@licPlateInput', formInfo.licPlate)
        .clearValue('@licStateInput')
        .setValue('@licStateInput', formInfo.licState)
        .clearValue('@licDateInput')
        .setValue('@licDateInput', formInfo.licDate)
}