module.exports = {
    allValidInput: [
        {
           header: 'We Must Save Ch1n@',
           mke: 'Mk#',
           oai:  '123456789',
           name: 'Fa Mulan',
           sex: 'F',              // Female
           race: 'A',         // A/Islander
           height: '504',
           weight: '130',
           hair: 'Black',
           offense: 'Dishonor',
           dow: '01012016',
           license: 'Abc123!@#',
           dlState: 'CA',
           dlDate: '12312018',
           licPlate: 'China15',
           licState: 'UT',
           licDate: '12252018',
        },
        {
            header: 'Can I Hum It',
            mke: 'Mk#',
            oai:  '123456789',
            name: 'Donkey',
            sex: 'M',              // Male
            race: 'B',         // Black
            height: '302',
            weight: '200',
            hair: 'Black',
            offense: 'Singing Too Loud',
            dow: '01012016',
            license: 'Abc123!@#',
            dlState: 'CA',
            dlDate: '12312018',
            licPlate: 'Donkey12',
            licState: 'UT',
            licDate: '12252018',
         },
         {
            header: 'Make All the Food',
            mke: 'Mk#',
            oai:  '123456789',
            name: 'Aaron Sanchez',
            sex: 'O',              // Other
            race: 'H',         // Hispanic
            height: '510',
            weight: '200',
            hair: 'Black',
            offense: 'Food w@s 2g00d',
            dow: '01012016',
            license: 'Abc123!@#',
            dlState: 'CA',
            dlDate: '12312018',
            licPlate: 'TacoLife',
            licState: 'UT',
            licDate: '12252018',
         },
         {
            header: 'ColorsOfTheWind',
            mke: 'Mk#',
            oai:  '123456789',
            name: 'Pocahontas',
            sex: 'U',                      // Unknown
            race: 'I',       // American Indian
            height: '504',
            weight: '130',
            hair: 'Black',
            offense: 'PaintedWColor',
            dow: '01012016',
            license: 'Abc123!@#',
            dlState: 'CA',
            dlDate: '12312018',
            licPlate: 'C0mpass',
            licState: 'UT',
            licDate: '12252018',
         },
         {
            header: 'Read Books',
            mke: 'Mk#',
            oai:  '123456789',
            name: 'Belle Beauty',
            sex: 'F',              
            race: 'W',         // White
            height: '504',
            weight: '130',
            hair: 'Brown',
            offense: 'SkippedDinner',
            dow: '01012016',
            license: 'Abc123!@#',
            dlState: 'CA',
            dlDate: '12312018',
            licPlate: 'Beast10',
            licState: 'UT',
            licDate: '12252018',
         },
         {
            header: 'LetDownYourHair',
            mke: 'Mk#',
            oai:  '123456789',
            name: 'Rapunzel',
            sex: 'F',              
            race: 'U',      // Unknown
            height: '504',
            weight: '130',
            hair: 'Blonde',
            offense: 'Ran away',
            dow: '01012016',
            license: 'Abc123!@#',
            dlState: 'CA',
            dlDate: '12312018',
            licPlate: 'Hair4dz',
            licState: 'UT',
            licDate: '12252018',
         },
    ],
    validSomeOptional: [
        {
           header: 'CleanItUp',
           mke: 'Mk%',
           oai:  '123456789',
           name: 'Cinderella',
           sex: 'F',
           race: 'W',
           height: '503',
           weight: '125',
           hair: 'Blonde',
           offense: 'WentToTheBall',
           dow: '01012018',
           license: 'Abc12345',   // only first optional set
           dlState: 'OR',
           dlDate: '12312018',
           licPlate: '',
           licState: '',
           licDate: '',
        },
        {
            header: 'CleanItUp',
            mke: 'Mk%',
            oai:  '123456789',
            name: 'Cinderella',
            sex: 'F',
            race: 'W',
            height: '503',
            weight: '125',
            hair: 'Blonde',
            offense: 'WentToTheBall',
            dow: '01012018',
            license: 'Abc12345',   // #1 of first opt set
            dlState: '',
            dlDate: '',
            licPlate: '',
            licState: '',
            licDate: '',
         },
         {
            header: 'CleanItUp',
            mke: 'Mk%',
            oai:  '123456789',
            name: 'Cinderella',
            sex: 'F',
            race: 'W',
            height: '503',
            weight: '125',
            hair: 'Blonde',
            offense: 'WentToTheBall',
            dow: '01012018',
            license: '',    // #2 of first opt set
            dlState: 'OR',
            dlDate: '',
            licPlate: '',
            licState: '',
            licDate: '',
         },
         {
            header: 'CleanItUp',
            mke: 'Mk%',
            oai:  '123456789',
            name: 'Cinderella',
            sex: 'F',
            race: 'W',
            height: '503',
            weight: '125',
            hair: 'Blonde',
            offense: 'WentToTheBall',
            dow: '01012018',
            license: '',    // #3 of first opt set
            dlState: '',
            dlDate: '12312018',
            licPlate: '',
            licState: '',
            licDate: '',
         },
         {
            header: 'CleanItUp',
            mke: 'Mk%',
            oai:  '123456789',
            name: 'Cinderella',
            sex: 'F',
            race: 'W',
            height: '503',
            weight: '125',
            hair: 'Blonde',
            offense: 'WentToTheBall',
            dow: '01012018',
            license: 'Abc12345',    // #1 and 2 of first opt set
            dlState: 'UT',
            dlDate: '',
            licPlate: '',
            licState: '',
            licDate: '',
         },
         {
            header: 'CleanItUp',
            mke: 'Mk%',
            oai:  '123456789',
            name: 'Cinderella',
            sex: 'F',
            race: 'W',
            height: '503',
            weight: '125',
            hair: 'Blonde',
            offense: 'WentToTheBall',
            dow: '01012018',
            license: '',    // #2 and 3 of first opt set
            dlState: 'UT',
            dlDate: '12312018',
            licPlate: '',
            licState: '',
            licDate: '',
         },
         {
            header: 'CleanItUp',
            mke: 'Mk%',
            oai:  '123456789',
            name: 'Cinderella',
            sex: 'F',
            race: 'W',
            height: '503',
            weight: '125',
            hair: 'Blonde',
            offense: 'WentToTheBall',
            dow: '01012018',
            license: 'Abc12345',    // #1 and 3 of first opt set
            dlState: '',
            dlDate: '12312018',
            licPlate: '',
            licState: '',
            licDate: '',
         },
         {
            header: 'CleanItUp',
            mke: 'Mk%',
            oai:  '123456789',
            name: 'Cinderella',
            sex: 'F',
            race: 'W',
            height: '503',
            weight: '125',
            hair: 'Blonde',
            offense: 'WentToTheBall',
            dow: '01012018',
            license: '',    // #1 of second opt set
            dlState: '',
            dlDate: '',
            licPlate: 'Abc123',
            licState: '',
            licDate: '',
         },
         {
            header: 'CleanItUp',
            mke: 'Mk%',
            oai:  '123456789',
            name: 'Cinderella',
            sex: 'F',
            race: 'W',
            height: '503',
            weight: '125',
            hair: 'Blonde',
            offense: 'WentToTheBall',
            dow: '01012018',
            license: '',    // #2 of second opt set
            dlState: '',
            dlDate: '',
            licPlate: '',
            licState: 'UT',
            licDate: '',
         },
         {
            header: 'CleanItUp',
            mke: 'Mk%',
            oai:  '123456789',
            name: 'Cinderella',
            sex: 'F',
            race: 'W',
            height: '503',
            weight: '125',
            hair: 'Blonde',
            offense: 'WentToTheBall',
            dow: '01012018',
            license: '',    // #3 of second opt set
            dlState: '',
            dlDate: '',
            licPlate: '',
            licState: '',
            licDate: '',
         },
         {
            header: 'CleanItUp',
            mke: 'Mk%',
            oai:  '123456789',
            name: 'Cinderella',
            sex: 'F',
            race: 'W',
            height: '503',
            weight: '125',
            hair: 'Blonde',
            offense: 'WentToTheBall',
            dow: '01012018',
            license: '',    // #1 and 2 of second opt set
            dlState: '',
            dlDate: '',
            licPlate: 'Abc123',
            licState: 'UT',
            licDate: '',
         },
         {
            header: 'CleanItUp',
            mke: 'Mk%',
            oai:  '123456789',
            name: 'Cinderella',
            sex: 'F',
            race: 'W',
            height: '503',
            weight: '125',
            hair: 'Blonde',
            offense: 'WentToTheBall',
            dow: '01012018',
            license: '',    // #2 and 3 of second opt set
            dlState: '',
            dlDate: '',
            licPlate: '',
            licState: 'UT',
            licDate: '12312018',
         },
         {
            header: 'CleanItUp',
            mke: 'Mk%',
            oai:  '123456789',
            name: 'Cinderella',
            sex: 'F',
            race: 'W',
            height: '503',
            weight: '125',
            hair: 'Blonde',
            offense: 'WentToTheBall',
            dow: '01012018',
            license: '',    // #1 and 3 of second opt set
            dlState: '',
            dlDate: '',
            licPlate: 'Abc123',
            licState: '',
            licDate: '12312018',
         },
         {
            header: 'CleanItUp',
            mke: 'Mk%',
            oai:  '123456789',
            name: 'Cinderella',
            sex: 'F',
            race: 'W',
            height: '503',
            weight: '125',
            hair: 'Blonde',
            offense: 'WentToTheBall',
            dow: '01012018',
            license: '',    // second opt set
            dlState: '',
            dlDate: '',
            licPlate: 'Abc123',
            licState: 'UT',
            licDate: '12312018',
         },
    ],
    invalidCharacterInput: [
        {
           header: 'Toy Story',
           mke: '123', // 2-4, alpha or special
           oai:  '123456789', 
           name: 'Buzz Lightyear', 
           sex: 'M', 
           race: 'W', 
           height: '600', 
           weight: '185', 
           hair: 'Bald', 
           offense: 'Star Command',
           dow: '01012018', 
           license: 'Abc123456',
           dlState: 'UT', 
           dlDate: '01012020',
           licPlate: 'StrCmd',
           licState: 'UT', 
           licDate: '12312020',
        },
        {
           header: 'Toy Story',
           mke: 'Abc', 
           oai:  '123456789',
           name: 'Buzz Lightyear',
           sex: '5', // 1, alpha only, F M or U
           race: 'W', 
           height: '600', 
           weight: '185', 
           hair: 'Bald', 
           offense: 'Star Command',
           dow: '01012018', 
           license: 'Abc123456', 
           dlState: 'UT', 
           dlDate: '01012020',
           licPlate: 'StrCmd',
           licState: 'UT', 
           licDate: '12312020',
        },
        {
           header: 'Toy Story',
           mke: 'Abc', 
           oai:  '123456789',
           name: 'Buzz Lightyear',
           sex: 'M', 
           race: '7', // 1, alphabet
           height: '600', 
           weight: '185', 
           hair: 'Bald', 
           offense: 'Star Command',
           dow: '01012018', 
           license: 'Abc123456',
           dlState: 'UT', 
           dlDate: '01012020',
           licPlate: 'StrCmd',
           licState: 'UT', 
           licDate: '12312020',
        },
        {
           header: 'Toy Story',
           mke: '123', 
           oai:  '123456789', 
           name: 'Buzz Lightyear',
           sex: 'M', 
           race: 'W',
           height: 'Abc', // 3, numeric
           weight: '185', 
           hair: 'Bald', 
           offense: 'Star Command',
           dow: '01012018', 
           license: 'Abc123456',
           dlState: 'UT', 
           dlDate: '01012020',
           licPlate: 'StrCmd',
           licState: 'UT', 
           licDate: '12312020',
        },
        {
           header: 'Toy Story',
           mke: '123', 
           oai:  '123456789',
           name: 'Buzz Lightyear',
           sex: 'M', 
           race: 'W',
           height: '600', 
           weight: 'Toy', // 1-3, numeric 
           hair: 'Bald', 
           offense: 'Star Command',
           dow: '01012018', 
           license: 'Abc123456',
           dlState: 'UT', 
           dlDate: '01012020',
           licPlate: 'StrCmd',
           licState: 'UT', 
           licDate: '12312020',
        },
        {
           header: 'Toy Story',
           mke: '123', 
           oai:  '123456789', 
           name: 'Buzz Lightyear', 
           sex: 'M', 
           race: 'W', 
           height: '600', 
           weight: '185', 
           hair: '1234', // 3-10, alphabet
           offense: 'Star Command', 
           dow: '01012018', 
           license: 'Abc123456', 
           dlState: 'UT', 
           dlDate: '01012020', 
           licPlate: 'StrCmd', 
           licState: 'UT', 
           licDate: '12312020', 
        },
        {
           header: 'Toy Story',
           mke: '123', 
           oai:  '123456789', 
           name: 'Buzz Lightyear',
           sex: 'M', 
           race: 'W', 
           height: '600', 
           weight: '185', 
           hair: '!@#$', // 3-10, alphabet
           offense: 'Star Command', 
           dow: '01012018', 
           license: 'Abc123456', 
           dlState: 'UT', 
           dlDate: '01012020', 
           licPlate: 'StrCmd', 
           licState: 'UT', 
           licDate: '12312020', 
        },
        {
           header: 'Toy Story',
           mke: '123', 
           oai:  '123456789', 
           name: 'Buzz Lightyear', 
           sex: 'M', 
           race: 'W', 
           height: '600', 
           weight: '185', 
           hair: 'Bald', 
           offense: 'Star Command', 
           dow: 'Iam a date', // 10, numeric MMDDYYYY 1900 to today +1
           license: 'Abc123456', 
           dlState: 'UT', 
           dlDate: '01012020', 
           licPlate: 'StrCmd', 
           licState: 'UT', 
           licDate: '12312020', 
        },
        {
           header: 'Toy Story',
           mke: '123', 
           oai:  '123456789', 
           name: 'Buzz Lightyear', 
           sex: 'M', 
           race: 'W', 
           height: '600', 
           weight: '185', 
           hair: 'Bald', 
           offense: 'Star Command', 
           dow: '!@#$%^&*()!', // 10, numeric MMDDYYYY 1900 to today +1
           license: 'Abc123456', 
           dlState: 'UT', 
           dlDate: '01012020', 
           licPlate: 'StrCmd', 
           licState: 'UT', 
           licDate: '12312020', 
        },
        {
           header: 'Toy Story',
           mke: '123', 
           oai:  '123456789', 
           name: 'Buzz Lightyear', 
           sex: 'M', 
           race: 'W', 
           height: '600', 
           weight: '185',
           hair: 'Bald', 
           offense: 'Star Command', 
           dow: '01012018', 
           license: 'Abc123456', 
           dlState: '12', // 2, alphabet, state abbreviations
           dlDate: '01012020', 
           licPlate: 'StrCmd', 
           licState: 'UT', 
           licDate: '12312020', 
        },
        {
           header: 'Toy Story',
           mke: '123', 
           oai:  '123456789', 
           name: 'Buzz Lightyear', 
           sex: 'M', 
           race: 'W', 
           height: '600', 
           weight: '185', 
           hair: 'Bald', 
           offense: 'Star Command', 
           dow: '01012018', 
           license: 'Abc123456', 
           dlState: '&*', // 2, alphabet, state abbreviations
           dlDate: '01012020', 
           licPlate: 'StrCmd', 
           licState: 'UT', 
           licDate: '12312020', 
        },
        {
           header: 'Toy Story',
           mke: '123', 
           oai:  '123456789', 
           name: 'Buzz Lightyear', 
           sex: 'M', 
           race: 'W', 
           height: '600', 
           weight: '185', 
           hair: 'Bald', 
           offense: 'Star Command', 
           dow: '01012018', 
           license: 'Abc123456', 
           dlState: 'UT', 
           dlDate: 'Iam a date', // 10, numeric MMDDYYYY
           licPlate: 'StrCmd',
           licState: 'UT', 
           licDate: '12312020', 
        },
        {
           header: 'Toy Story',
           mke: '123', 
           oai:  '123456789', 
           name: 'Buzz Lightyear', 
           sex: 'M', 
           race: 'W', 
           height: '600', 
           weight: '185', 
           hair: 'Bald', 
           offense: 'Star Command', 
           dow: '01012018',
           license: 'Abc123456', 
           dlState: 'UT', 
           dlDate: '!@#$%^&*()', // 10, numeric MMDDYYYY
           licPlate: 'StrCmd', 
           licState: 'UT', 
           licDate: '12312020', 
        },
        {
           header: 'Toy Story',
           mke: '123', 
           oai:  '123456789', 
           name: 'Buzz Lightyear', 
           sex: 'M', 
           race: 'W', 
           height: '600', 
           weight: '185', 
           hair: 'Bald', 
           offense: 'Star Command', 
           dow: '01012018', 
           license: 'Abc123456', 
           dlState: 'UT', 
           dlDate: '01012020', 
           licPlate: '!@#$%^', // 5-8, aplphanumeric
           licState: 'UT', 
           licDate: '12312020', 
        },
        {
           header: 'Toy Story',
           mke: '123', 
           oai:  '123456789', 
           name: 'Buzz Lightyear',
           sex: 'M', 
           race: 'W', 
           height: '600', 
           weight: '185', 
           hair: 'Bald', 
           offense: 'Star Command', 
           dow: '01012018', 
           license: 'Abc123456', 
           dlState: 'UT', 
           dlDate: '01012020', 
           licPlate: 'StrCmd', 
           licState: '12', // 2, alphabet, state abbreviations
           licDate: '12312020', 
        },
        {
           header: 'Toy Story',
           mke: '123', 
           oai:  '123456789', 
           name: 'Buzz Lightyear',
           sex: 'M', 
           race: 'W', 
           height: '600', 
           weight: '185', 
           hair: 'Bald', 
           offense: 'Star Command', 
           dow: '01012018', 
           license: 'Abc123456', 
           dlState: 'UT', 
           dlDate: '01012020', 
           licPlate: 'StrCmd', 
           licState: '!@', // 2, alphabet, state abbreviations
           licDate: '12312020', 
        },
        {
           header: 'Toy Story',
           mke: '123', 
           oai:  '123456789', 
           name: 'Buzz Lightyear',
           sex: 'M', 
           race: 'W', 
           height: '600', 
           weight: '185', 
           hair: 'Bald', 
           offense: 'Star Command', 
           dow: '01012018', 
           license: 'Abc123456', 
           dlState: 'UT', 
           dlDate: '01012020', 
           licPlate: 'StrCmd', 
           licState: 'UT',
           licDate: 'Iam a date', // 10, numeric, state abbreviations
        },
        {
           header: 'Toy Story',
           mke: '123', 
           oai:  '123456789', 
           name: 'Buzz Lightyear',
           sex: 'M', 
           race: 'W', 
           height: '600', 
           weight: '185', 
           hair: 'Bald', 
           offense: 'Star Command', 
           dow: '01012018', 
           license: 'Abc123456', 
           dlState: 'UT', 
           dlDate: '01012020', 
           licPlate: 'StrCmd', 
           licState: '12', 
           licDate: '!@#$%^&*()', // 10, numeric, state abbreviations
        },
    ],
    insufficientLengthInput: [
        {
           header: 'BeautyBe',
           mke: 'BNB',
           oai:  '123456789',
           name: 'Belle',
           sex: 'F',
           race: 'W',
           height: '503',
           weight: '120',
           hair: 'Brown',
           offense: 'TookDadsPlace',
           dow: '01012018',
           license: 'Abc1234',
           dlState: 'UT',
           dlDate: '12312020',
           licPlate: 'BEAUTY6',
           licState: 'UT',
           licDate: '12252020',
        },
        {
           header: 'Beauty & the Beast',
           mke: 'B',
           oai:  '12345678',
           name: 'Be',
           sex: 'F',
           race: 'W',
           height: '503',
           weight: '120',
           hair: 'Brown',
           offense: 'TookDadsPlace',
           dow: '01012018',
           license: 'Abc1234',
           dlState: 'UT',
           dlDate: '12312020',
           licPlate: 'BEAUTY6',
           licState: 'UT',
           licDate: '12252020',
        },
        {
           header: 'Beauty & the Beast',
           mke: 'BNB',
           oai:  '123456789',
           name: 'Belle',
           sex: 'F',
           race: 'W',
           height: '50',
           weight: '120',
           hair: 'Brown',
           offense: 'TookDadsPlace',
           dow: '01012018',
           license: 'Abc1234',
           dlState: 'UT',
           dlDate: '12312020',
           licPlate: 'BEAUTY6',
           licState: 'UT',
           licDate: '12252020',
        },
        {
           header: 'Beauty & the Beast',
           mke: 'BNB',
           oai:  '123456789',
           name: 'Belle',
           sex: 'F',
           race: 'W',
           height: '503',
           weight: '120',
           hair: 'Br',
           offense: 'TookDadsPlace',
           dow: '01012018',
           license: 'Abc1234',
           dlState: 'UT',
           dlDate: '12312020',
           licPlate: 'BEAUTY6',
           licState: 'UT',
           licDate: '12252020',
        },
        {
           header: 'Beauty & the Beast',
           mke: 'BNB',
           oai:  '123456789',
           name: 'Belle',
           sex: 'F',
           race: 'W',
           height: '503',
           weight: '120',
           hair: 'Brown',
           offense: 'Read',
           dow: '01012018',
           license: 'Abc1234',
           dlState: 'UT',
           dlDate: '12312020',
           licPlate: 'BEAUTY6',
           licState: 'UT',
           licDate: '12252020',
        },
        {
           header: 'Beauty & the Beast',
           mke: 'BNB',
           oai:  '123456789',
           name: 'Belle',
           sex: 'F',
           race: 'W',
           height: '503',
           weight: '120',
           hair: 'Brown',
           offense: 'TookDadsPlace',
           dow: '010120189',
           license: 'Abc1234',
           dlState: 'UT',
           dlDate: '12312020',
           licPlate: 'BEAUTY6',
           licState: 'UT',
           licDate: '12252020',
        },
        {
           header: 'Beauty & the Beast',
           mke: 'BNB',
           oai:  '123456789',
           name: 'Belle',
           sex: 'F',
           race: 'W',
           height: '503',
           weight: '120',
           hair: 'Brown',
           offense: 'TookDadsPlace',
           dow: '01012018',
           license: 'Abc1234',
           dlState: 'U',
           dlDate: '12312020',
           licPlate: 'BEAUTY6',
           licState: 'UT',
           licDate: '12252020',
        },
        {
           header: 'Beauty & the Beast',
           mke: 'BNB',
           oai:  '123456789',
           name: 'Belle',
           sex: 'F',
           race: 'W',
           height: '503',
           weight: '120',
           hair: 'Brown',
           offense: 'TookDadsPlace',
           dow: '01012018',
           license: 'Abc1234',
           dlState: 'UT',
           dlDate: '123120209',
           licPlate: 'BEAUTY6',
           licState: 'UT',
           licDate: '12252020',
        },
        {
           header: 'Beauty & the Beast',
           mke: 'BNB',
           oai:  '123456789',
           name: 'Belle',
           sex: 'F',
           race: 'W',
           height: '503',
           weight: '120',
           hair: 'Brown',
           offense: 'TookDadsPlace',
           dow: '01012018',
           license: 'Abc1234',
           dlState: 'UT',
           dlDate: '12312020',
           licPlate: 'BEAU',
           licState: 'UT',
           licDate: '12252020',
        },
        {
           header: 'Beauty & the Beast',
           mke: 'BNB',
           oai:  '123456789',
           name: 'Belle',
           sex: 'F',
           race: 'W',
           height: '503',
           weight: '120',
           hair: 'Brown',
           offense: 'TookDadsPlace',
           dow: '01012018',
           license: 'Abc1234',
           dlState: 'UT',
           dlDate: '12312020',
           licPlate: 'BEAUTY6',
           licState: 'U',
           licDate: '12252020',
        },
        {
           header: 'Beauty & the Beast',
           mke: 'BNB',
           oai:  '123456789',
           name: 'Belle',
           sex: 'F',
           race: 'W',
           height: '503',
           weight: '120',
           hair: 'Brown',
           offense: 'TookDadsPlace',
           dow: '01012018',
           license: 'Abc1234',
           dlState: 'UT',
           dlDate: '12312020',
           licPlate: 'BEAUTY6',
           licState: 'UT',
           licDate: '122520209',
        },
    ],
    excessiveLengthInput: [
        {
           header: 'Winnie the Pooh Winn',
           mke: 'Win',
           oai:  '123456789',
           name: 'Tigger',
           sex: 'M',
           race: 'I',
           height: '402',
           weight: '075',
           hair: 'Striped',
           offense: 'BouncedTooMuch',
           dow: '01012018',
           license: 'Abc1234',
           dlState: 'WA',
           dlDate: '12312025',
           licPlate: 'TIGGER',
           licState: 'WA',
           licDate: '12252020',
        },
        {
           header: 'Winnie the Pooh',
           mke: 'Winni',
           oai:  '123456789',
           name: 'Tigger',
           sex: 'M',
           race: 'I',
           height: '402',
           weight: '075',
           hair: 'Striped',
           offense: 'BouncedTooMuch',
           dow: '01012018',
           license: 'Abc1234',
           dlState: 'WA',
           dlDate: '12312025',
           licPlate: 'TIGGER',
           licState: 'WA',
           licDate: '12252020',
        },
        {
           header: 'Winnie the Pooh',
           mke: 'Win',
           oai:  '1234567890',
           name: 'Tigger',
           sex: 'M',
           race: 'I',
           height: '402',
           weight: '075',
           hair: 'Striped',
           offense: 'BouncedTooMuch',
           dow: '01012018',
           license: 'Abc1234',
           dlState: 'WA',
           dlDate: '12312025',
           licPlate: 'TIGGER',
           licState: 'WA',
           licDate: '12252020',
        },
        {
           header: 'Winnie the Pooh',
           mke: 'Win',
           oai:  '123456789',
           name: 'TiggerTiggerTiggerTiggerTiggerT',
           sex: 'M',
           race: 'I',
           height: '402',
           weight: '075',
           hair: 'Striped',
           offense: 'BouncedTooMuch',
           dow: '01012018',
           license: 'Abc1234',
           dlState: 'WA',
           dlDate: '12312025',
           licPlate: 'TIGGER',
           licState: 'WA',
           licDate: '12252020',
        },
        {
           header: 'Winnie the Pooh',
           mke: 'Win',
           oai:  '123456789',
           name: 'Tigger',
           sex: 'Ma',
           race: 'I',
           height: '402',
           weight: '075',
           hair: 'Striped',
           offense: 'BouncedTooMuch',
           dow: '01012018',
           license: 'Abc1234',
           dlState: 'WA',
           dlDate: '12312025',
           licPlate: 'TIGGER',
           licState: 'WA',
           licDate: '12252020',
        },
        {
           header: 'Winnie the Pooh',
           mke: 'Win',
           oai:  '123456789',
           name: 'Tigger',
           sex: 'M',
           race: 'In',
           height: '402',
           weight: '075',
           hair: 'Striped',
           offense: 'BouncedTooMuch',
           dow: '01012018',
           license: 'Abc1234',
           dlState: 'WA',
           dlDate: '12312025',
           licPlate: 'TIGGER',
           licState: 'WA',
           licDate: '12252020',
        },
        {
           header: 'Winnie the Pooh',
           mke: 'Win',
           oai:  '123456789',
           name: 'Tigger',
           sex: 'M',
           race: 'I',
           height: '4021',
           weight: '075',
           hair: 'Striped',
           offense: 'BouncedTooMuch',
           dow: '01012018',
           license: 'Abc1234',
           dlState: 'WA',
           dlDate: '12312025',
           licPlate: 'TIGGER',
           licState: 'WA',
           licDate: '12252020',
        },
        {
           header: 'Winnie the Pooh',
           mke: 'Win',
           oai:  '123456789',
           name: 'Tigger',
           sex: 'M',
           race: 'I',
           height: '402',
           weight: '0751',
           hair: 'Striped',
           offense: 'BouncedTooMuch',
           dow: '01012018',
           license: 'Abc1234',
           dlState: 'WA',
           dlDate: '12312025',
           licPlate: 'TIGGER',
           licState: 'WA',
           licDate: '12252020',
        },
        {
           header: 'Winnie the Pooh',
           mke: 'Win',
           oai:  '123456789',
           name: 'Tigger',
           sex: 'M',
           race: 'I',
           height: '402',
           weight: '075',
           hair: 'StripedStri',
           offense: 'BouncedTooMuch',
           dow: '01012018',
           license: 'Abc1234',
           dlState: 'WA',
           dlDate: '12312025',
           licPlate: 'TIGGER',
           licState: 'WA',
           licDate: '12252020',
        },
        {
           header: 'Winnie the Pooh',
           mke: 'Win',
           oai:  '123456789',
           name: 'Tigger',
           sex: 'M',
           race: 'I',
           height: '402',
           weight: '075',
           hair: 'Striped',
           offense: 'BouncedTooMuchBo',
           dow: '01012018',
           license: 'Abc1234',
           dlState: 'WA',
           dlDate: '12312025',
           licPlate: 'TIGGER',
           licState: 'WA',
           licDate: '12252020',
        },
        {
           header: 'Winnie the Pooh',
           mke: 'Win',
           oai:  '123456789',
           name: 'Tigger',
           sex: 'M',
           race: 'I',
           height: '402',
           weight: '075',
           hair: 'Striped',
           offense: 'BouncedTooMuch',
           dow: '01012018201',
           license: 'Abc1234',
           dlState: 'WA',
           dlDate: '12312025',
           licPlate: 'TIGGER',
           licState: 'WA',
           licDate: '12252020',
        },
        {
           header: 'Winnie the Pooh',
           mke: 'Win',
           oai:  '123456789',
           name: 'Tigger',
           sex: 'M',
           race: 'I',
           height: '402',
           weight: '075',
           hair: 'Striped',
           offense: 'BouncedTooMuch',
           dow: '01012018',
           license: 'Abc12Abc12Abc12Abc12A',
           dlState: 'WA',
           dlDate: '12312025',
           licPlate: 'TIGGER',
           licState: 'WA',
           licDate: '12252020',
        },
        {
           header: 'Winnie the Pooh',
           mke: 'Win',
           oai:  '123456789',
           name: 'Tigger',
           sex: 'M',
           race: 'I',
           height: '402',
           weight: '075',
           hair: 'Striped',
           offense: 'BouncedTooMuch',
           dow: '01012018',
           license: 'Abc1234',
           dlState: 'WAs',
           dlDate: '12312025',
           licPlate: 'TIGGER',
           licState: 'WA',
           licDate: '12252020',
        },
        {
           header: 'Winnie the Pooh',
           mke: 'Win',
           oai:  '123456789',
           name: 'Tigger',
           sex: 'M',
           race: 'I',
           height: '402',
           weight: '075',
           hair: 'Striped',
           offense: 'BouncedTooMuch',
           dow: '01012018',
           license: 'Abc1234',
           dlState: 'WA',
           dlDate: '12312025202',
           licPlate: 'TIGGER',
           licState: 'WA',
           licDate: '12252020',
        },
        {
           header: 'Winnie the Pooh',
           mke: 'Win',
           oai:  '123456789',
           name: 'Tigger',
           sex: 'M',
           race: 'I',
           height: '402',
           weight: '075',
           hair: 'Striped',
           offense: 'BouncedTooMuch',
           dow: '01012018',
           license: 'Abc1234',
           dlState: 'WA',
           dlDate: '12312025',
           licPlate: 'TIGGERTIG',
           licState: 'WA',
           licDate: '12252020',
        },
        {
           header: 'Winnie the Pooh',
           mke: 'Win',
           oai:  '123456789',
           name: 'Tigger',
           sex: 'M',
           race: 'I',
           height: '402',
           weight: '075',
           hair: 'Striped',
           offense: 'BouncedTooMuch',
           dow: '01012018',
           license: 'Abc1234',
           dlState: 'WA',
           dlDate: '12312025',
           licPlate: 'TIGGER',
           licState: 'WAs',
           licDate: '12252020',
        },
        {
           header: 'Winnie the Pooh',
           mke: 'Win',
           oai:  '123456789',
           name: 'Tigger',
           sex: 'M',
           race: 'I',
           height: '402',
           weight: '075',
           hair: 'Striped',
           offense: 'BouncedTooMuch',
           dow: '01012018',
           license: 'Abc1234',
           dlState: 'WA',
           dlDate: '12312025',
           licPlate: 'TIGGER',
           licState: 'WA',
           licDate: '12252020202',
        },
    ],
    requiredFieldsIncomplete: [
        {
           header: ' \uE003',
           mke: 'Car',
           oai:  '123456789',
           name: 'Lightning McQueen',
           sex: 'M',
           race: 'W',
           height: '306',
           weight: '800',
           hair: 'Red',
           offense: 'Speeding',
           dow: '01012018',
           license: 'Abc12345',
           dlState: 'AZ',
           dlDate: '12312020',
           licPlate: 'SPEED',
           licState: 'AZ',
           licDate: '12252025',
        },
        {
           header: 'We are Cars',
           mke: ' \uE003',
           oai:  '123456789',
           name: 'Lightning McQueen',
           sex: 'M',
           race: 'W',
           height: '306',
           weight: '800',
           hair: 'Red',
           offense: 'Speeding',
           dow: '01012018',
           license: 'Abc12345',
           dlState: 'AZ',
           dlDate: '12312020',
           licPlate: 'SPEED',
           licState: 'AZ',
           licDate: '12252025',
        },
        {
           header: 'We are Cars',
           mke: 'Car',
           oai:  ' \uE003',
           name: 'Lightning McQueen',
           sex: 'M',
           race: 'W',
           height: '306',
           weight: '800',
           hair: 'Red',
           offense: 'Speeding',
           dow: '01012018',
           license: 'Abc12345',
           dlState: 'AZ',
           dlDate: '12312020',
           licPlate: 'SPEED',
           licState: 'AZ',
           licDate: '12252025',
        },
        {
           header: 'We are Cars',
           mke: 'Car',
           oai:  '123456789',
           name: ' \uE003',
           sex: 'M',
           race: 'W',
           height: '306',
           weight: '800',
           hair: 'Red',
           offense: 'Speeding',
           dow: '01012018',
           license: 'Abc12345',
           dlState: 'AZ',
           dlDate: '12312020',
           licPlate: 'SPEED',
           licState: 'AZ',
           licDate: '12252025',
        },
        {
           header: 'We are Cars',
           mke: 'Car',
           oai:  '123456789',
           name: 'Lightning McQueen',
           sex: ' \uE003',
           race: 'W',
           height: '306',
           weight: '800',
           hair: 'Red',
           offense: 'Speeding',
           dow: '01012018',
           license: 'Abc12345',
           dlState: 'AZ',
           dlDate: '12312020',
           licPlate: 'SPEED',
           licState: 'AZ',
           licDate: '12252025',
        },
        {
           header: 'We are Cars',
           mke: 'Car',
           oai:  '123456789',
           name: 'Lightning McQueen',
           sex: 'M',
           race: ' \uE003',
           height: '306',
           weight: '800',
           hair: 'Red',
           offense: 'Speeding',
           dow: '01012018',
           license: 'Abc12345',
           dlState: 'AZ',
           dlDate: '12312020',
           licPlate: 'SPEED',
           licState: 'AZ',
           licDate: '12252025',
        },
        {
           header: 'We are Cars',
           mke: 'Car',
           oai:  '123456789',
           name: 'Lightning McQueen',
           sex: 'M',
           race: 'W',
           height: ' \uE003',
           weight: '800',
           hair: 'Red',
           offense: 'Speeding',
           dow: '01012018',
           license: 'Abc12345',
           dlState: 'AZ',
           dlDate: '12312020',
           licPlate: 'SPEED',
           licState: 'AZ',
           licDate: '12252025',
        },
        {
           header: 'We are Cars',
           mke: 'Car',
           oai:  '123456789',
           name: 'Lightning McQueen',
           sex: 'M',
           race: 'W',
           height: '306',
           weight: ' \uE003',
           hair: 'Red',
           offense: 'Speeding',
           dow: '01012018',
           license: 'Abc12345',
           dlState: 'AZ',
           dlDate: '12312020',
           licPlate: 'SPEED',
           licState: 'AZ',
           licDate: '12252025',
        },
        {
           header: 'We are Cars',
           mke: 'Car',
           oai:  '123456789',
           name: 'Lightning McQueen',
           sex: 'M',
           race: 'W',
           height: '306',
           weight: '800',
           hair: ' \uE003',
           offense: 'Speeding',
           dow: '01012018',
           license: 'Abc12345',
           dlState: 'AZ',
           dlDate: '12312020',
           licPlate: 'SPEED',
           licState: 'AZ',
           licDate: '12252025',
        },
        {
           header: 'We are Cars',
           mke: 'Car',
           oai:  '123456789',
           name: 'Lightning McQueen',
           sex: 'M',
           race: 'W',
           height: '306',
           weight: '800',
           hair: 'Red',
           offense: ' \uE003',
           dow: '01012018',
           license: 'Abc12345',
           dlState: 'AZ',
           dlDate: '12312020',
           licPlate: 'SPEED',
           licState: 'AZ',
           licDate: '12252025',
        },
        {
           header: 'We are Cars',
           mke: 'Car',
           oai:  '123456789',
           name: 'Lightning McQueen',
           sex: 'M',
           race: 'W',
           height: '306',
           weight: '800',
           hair: 'Red',
           offense: 'Speeding',
           dow: ' \uE003',
           license: 'Abc12345',
           dlState: 'AZ',
           dlDate: '12312020',
           licPlate: 'SPEED',
           licState: 'AZ',
           licDate: '12252025',
        },
    ],
    validBoundaryValues: [
        {
           header: 'PrinceAli',
           mke: 'Lad',
           oai:  '123456789',
           name: 'Aladdin',
           sex: 'M',
           race: 'U',
           height: '510',
           weight: '150',
           hair: 'Black',
           offense: 'Stole some bread',
           dow: '02022018',
           license: 'Abc1234',
           dlState: 'NJ',
           dlDate: '11112021',
           licPlate: 'GENIE',
           licState: 'NJ',
           licDate: '12122022',
        },
        {
           header: 'Prince Ali Abba Bwa',
           mke: 'Lad',
           oai:  '123456789',
           name: 'Aladdin',
           sex: 'M',
           race: 'U',
           height: '510',
           weight: '150',
           hair: 'Black',
           offense: 'Stole some bread',
           dow: '02022018',
           license: 'Abc1234',
           dlState: 'NJ',
           dlDate: '11112021',
           licPlate: 'GENIE',
           licState: 'NJ',
           licDate: '12122022',
        },
        {
           header: 'Prince Ali',
           mke: 'La',
           oai:  '123456789',
           name: 'Aladdin',
           sex: 'M',
           race: 'U',
           height: '510',
           weight: '150',
           hair: 'Black',
           offense: 'Stole some bread',
           dow: '02022018',
           license: 'Abc1234',
           dlState: 'NJ',
           dlDate: '11112021',
           licPlate: 'GENIE',
           licState: 'NJ',
           licDate: '12122022',
        },
        {
           header: 'Prince Ali',
           mke: 'Ladd',
           oai:  '123456789',
           name: 'Aladdin',
           sex: 'M',
           race: 'U',
           height: '510',
           weight: '150',
           hair: 'Black',
           offense: 'Stole some bread',
           dow: '02022018',
           license: 'Abc1234',
           dlState: 'NJ',
           dlDate: '11112021',
           licPlate: 'GENIE',
           licState: 'NJ',
           licDate: '12122022',
        },
        {
           header: 'Prince Ali',
           mke: 'Lad',
           oai:  '123456789',
           name: 'Aladdin',
           sex: 'M',
           race: 'U',
           height: '510',
           weight: '150',
           hair: 'Black',
           offense: 'Stole some bread',
           dow: '02022018',
           license: 'Abc1234',
           dlState: 'NJ',
           dlDate: '11112021',
           licPlate: 'GENIE',
           licState: 'NJ',
           licDate: '12122022',
        },
        {
           header: 'Prince Ali',
           mke: 'Lad',
           oai:  '123456789',
           name: 'Ala',
           sex: 'M',
           race: 'U',
           height: '510',
           weight: '150',
           hair: 'Black',
           offense: 'Stole some bread',
           dow: '02022018',
           license: 'Abc1234',
           dlState: 'NJ',
           dlDate: '11112021',
           licPlate: 'GENIE',
           licState: 'NJ',
           licDate: '12122022',
        },
        {
           header: 'Prince Ali',
           mke: 'Lad',
           oai:  '123456789',
           name: 'Aladdin Aladdin',
           sex: 'M',
           race: 'U',
           height: '510',
           weight: '150',
           hair: 'Black',
           offense: 'Stole some bread',
           dow: '02022018',
           license: 'Abc1234',
           dlState: 'NJ',
           dlDate: '11112021',
           licPlate: 'GENIE',
           licState: 'NJ',
           licDate: '12122022',
        },
        {
           header: 'Prince Ali',
           mke: 'Lad',
           oai:  '123456789',
           name: 'AladdinAladdinAladdinAla',
           sex: 'M',
           race: 'U',
           height: '510',
           weight: '150',
           hair: 'Black',
           offense: 'Stole some bread',
           dow: '02022018',
           license: 'Abc1234',
           dlState: 'NJ',
           dlDate: '11112021',
           licPlate: 'GENIE',
           licState: 'NJ',
           licDate: '12122022',
        },
        {
           header: 'Prince Ali',
           mke: 'Lad',
           oai:  '123456789',
           name: 'Aladdin',
           sex: 'M',
           race: 'U',
           height: '510',
           weight: '150',
           hair: 'Black',
           offense: 'Stole some bread',
           dow: '02022018',
           license: 'Abc1234',
           dlState: 'NJ',
           dlDate: '11112021',
           licPlate: 'GENIE',
           licState: 'NJ',
           licDate: '12122022',
        },
        {
           header: 'Prince Ali',
           mke: 'Lad',
           oai:  '123456789',
           name: 'Aladdin',
           sex: 'M',
           race: 'U',
           height: '510',
           weight: '150',
           hair: 'Black',
           offense: 'Stole some bread',
           dow: '02022018',
           license: 'Abc1234',
           dlState: 'NJ',
           dlDate: '11112021',
           licPlate: 'GENIE',
           licState: 'NJ',
           licDate: '12122022',
        },
        {
           header: 'Prince Ali',
           mke: 'Lad',
           oai:  '123456789',
           name: 'Aladdin',
           sex: 'M',
           race: 'U',
           height: '510',
           weight: '150',
           hair: 'Black',
           offense: 'Stole some bread',
           dow: '02022018',
           license: 'Abc1234',
           dlState: 'NJ',
           dlDate: '11112021',
           licPlate: 'GENIE',
           licState: 'NJ',
           licDate: '12122022',
        },
        {
           header: 'Prince Ali',
           mke: 'Lad',
           oai:  '123456789',
           name: 'Aladdin',
           sex: 'M',
           race: 'U',
           height: '510',
           weight: '1',
           hair: 'Black',
           offense: 'Stole some bread',
           dow: '02022018',
           license: 'Abc1234',
           dlState: 'NJ',
           dlDate: '11112021',
           licPlate: 'GENIE',
           licState: 'NJ',
           licDate: '12122022',
        },
        {
           header: 'Prince Ali',
           mke: 'Lad',
           oai:  '123456789',
           name: 'Aladdin',
           sex: 'M',
           race: 'U',
           height: '510',
           weight: '150',
           hair: 'Black',
           offense: 'Stole some bread',
           dow: '02022018',
           license: 'Abc1234',
           dlState: 'NJ',
           dlDate: '11112021',
           licPlate: 'GENIE',
           licState: 'NJ',
           licDate: '12122022',
        },
        {
           header: 'Prince Ali',
           mke: 'Lad',
           oai:  '123456789',
           name: 'Aladdin',
           sex: 'M',
           race: 'U',
           height: '510',
           weight: '150',
           hair: 'Bla',
           offense: 'Stole some bread',
           dow: '02022018',
           license: 'Abc1234',
           dlState: 'NJ',
           dlDate: '11112021',
           licPlate: 'GENIE',
           licState: 'NJ',
           licDate: '12122022',
        },
        {
           header: 'Prince Ali',
           mke: 'Lad',
           oai:  '123456789',
           name: 'Aladdin',
           sex: 'M',
           race: 'U',
           height: '510',
           weight: '150',
           hair: 'BlackBlack',
           offense: 'Stole some bread',
           dow: '02022018',
           license: 'Abc1234',
           dlState: 'NJ',
           dlDate: '11112021',
           licPlate: 'GENIE',
           licState: 'NJ',
           licDate: '12122022',
        },
        {
           header: 'Prince Ali',
           mke: 'Lad',
           oai:  '123456789',
           name: 'Aladdin',
           sex: 'M',
           race: 'U',
           height: '510',
           weight: '150',
           hair: 'Black',
           offense: 'Stole',
           dow: '02022018',
           license: 'Abc1234',
           dlState: 'NJ',
           dlDate: '11112021',
           licPlate: 'GENIE',
           licState: 'NJ',
           licDate: '12122022',
        },
        {
           header: 'Prince Ali',
           mke: 'Lad',
           oai:  '123456789',
           name: 'Aladdin',
           sex: 'M',
           race: 'U',
           height: '510',
           weight: '150',
           hair: 'Black',
           offense: 'StoleBreadStole',
           dow: '02022018',
           license: 'Abc1234',
           dlState: 'NJ',
           dlDate: '11112021',
           licPlate: 'GENIE',
           licState: 'NJ',
           licDate: '12122022',
        },
        {
           header: 'Prince Ali',
           mke: 'Lad',
           oai:  '123456789',
           name: 'Aladdin',
           sex: 'M',
           race: 'U',
           height: '510',
           weight: '150',
           hair: 'Black',
           offense: 'Stole some bread',
           dow: '0202201820',
           license: 'Abc1234',
           dlState: 'NJ',
           dlDate: '11112021',
           licPlate: 'GENIE',
           licState: 'NJ',
           licDate: '12122022',
        },
        {
           header: 'Prince Ali',
           mke: 'Lad',
           oai:  '123456789',
           name: 'Aladdin',
           sex: 'M',
           race: 'U',
           height: '510',
           weight: '150',
           hair: 'Black',
           offense: 'Stole some bread',
           dow: '02022018',
           license: 'A',
           dlState: 'NJ',
           dlDate: '11112021',
           licPlate: 'GENIE',
           licState: 'NJ',
           licDate: '12122022',
        },
        {
           header: 'Prince Ali',
           mke: 'Lad',
           oai:  '123456789',
           name: 'Aladdin',
           sex: 'M',
           race: 'U',
           height: '510',
           weight: '150',
           hair: 'Black',
           offense: 'Stole some bread',
           dow: '02022018',
           license: 'Abc12Abc12',
           dlState: 'NJ',
           dlDate: '11112021',
           licPlate: 'GENIE',
           licState: 'NJ',
           licDate: '12122022',
        },
        {
           header: 'Prince Ali',
           mke: 'Lad',
           oai:  '123456789',
           name: 'Aladdin',
           sex: 'M',
           race: 'U',
           height: '510',
           weight: '150',
           hair: 'Black',
           offense: 'Stole some bread',
           dow: '02022018',
           license: 'Abc12Abc12Abc12Abc12',
           dlState: 'NJ',
           dlDate: '11112021',
           licPlate: 'GENIE',
           licState: 'NJ',
           licDate: '12122022',
        },
        {
           header: 'Prince Ali',
           mke: 'Lad',
           oai:  '123456789',
           name: 'Aladdin',
           sex: 'M',
           race: 'U',
           height: '510',
           weight: '150',
           hair: 'Black',
           offense: 'Stole some bread',
           dow: '02022018',
           license: 'Abc12',
           dlState: 'NJ',
           dlDate: '11112021',
           licPlate: 'GENIE',
           licState: 'NJ',
           licDate: '12122022',
        },
        {
           header: 'Prince Ali',
           mke: 'Lad',
           oai:  '123456789',
           name: 'Aladdin',
           sex: 'M',
           race: 'U',
           height: '510',
           weight: '150',
           hair: 'Black',
           offense: 'Stole some bread',
           dow: '02022018',
           license: 'Abc12',
           dlState: 'NJ',
           dlDate: '1111202120',
           licPlate: 'GENIE',
           licState: 'NJ',
           licDate: '12122022',
        },
        {
           header: 'Prince Ali',
           mke: 'Lad',
           oai:  '123456789',
           name: 'Aladdin',
           sex: 'M',
           race: 'U',
           height: '510',
           weight: '150',
           hair: 'Black',
           offense: 'Stole some bread',
           dow: '02022018',
           license: 'Abc12',
           dlState: 'NJ',
           dlDate: '11112021',
           licPlate: 'GENIE',
           licState: 'NJ',
           licDate: '12122022',
        },
        {
           header: 'Prince Ali',
           mke: 'Lad',
           oai:  '123456789',
           name: 'Aladdin',
           sex: 'M',
           race: 'U',
           height: '510',
           weight: '150',
           hair: 'Black',
           offense: 'Stole some bread',
           dow: '02022018',
           license: 'Abc12',
           dlState: 'NJ',
           dlDate: '11112021',
           licPlate: 'GENIELMP',
           licState: 'NJ',
           licDate: '12122022',
        },
        {
           header: 'Prince Ali',
           mke: 'Lad',
           oai:  '123456789',
           name: 'Aladdin',
           sex: 'M',
           race: 'U',
           height: '510',
           weight: '150',
           hair: 'Black',
           offense: 'Stole some bread',
           dow: '02022018',
           license: 'Abc12',
           dlState: 'NJ',
           dlDate: '11112021',
           licPlate: 'GENIE',
           licState: 'NJ',
           licDate: '1212202220',
        },
    ],
    validWidInput: [
        {
            wid: '1234567890',
            header: 'We Must Save Ch1n@',
            mke: 'Mk#',
            oai:  '123456789',
            name: 'Fa Mulan',
            sex: 'F',         
            race: 'A',        
            height: '504',
            weight: '130',
            hair: 'Black',
            offense: 'Dishonor',
            dow: '01012016',
            license: 'Abc123!@#',
            dlState: 'CA',
            dlDate: '12312018',
            licPlate: 'China15',
            licState: 'UT',
            licDate: '12252018',
        },
    ],
    invalidWidInput: [
        {
            wid: ' \uE003',
            header: 'We Must Save Ch1n@',
            mke: 'Mk#',
            oai:  '123456789',
            name: 'Fa Mulan',
            sex: 'F',         
            race: 'A',        
            height: '504',
            weight: '130',
            hair: 'Black',
            offense: 'Dishonor',
            dow: '01012016',
            license: 'Abc123!@#',
            dlState: 'CA',
            dlDate: '12312018',
            licPlate: 'China15',
            licState: 'UT',
            licDate: '12252018',
        },
        {
            wid: '1',
            header: 'We Must Save Ch1n@',
            mke: 'Mk#',
            oai:  '123456789',
            name: 'Fa Mulan',
            sex: 'F',        
            race: 'A',       
            height: '504',
            weight: '130',
            hair: 'Black',
            offense: 'Dishonor',
            dow: '01012016',
            license: 'Abc123!@#',
            dlState: 'CA',
            dlDate: '12312018',
            licPlate: 'China15',
            licState: 'UT',
            licDate: '12252018',
        },
        {
            wid: '123456789',
            header: 'We Must Save Ch1n@',
            mke: 'Mk#',
            oai:  '123456789',
            name: 'Fa Mulan',
            sex: 'F',          
            race: 'A',         
            height: '504',
            weight: '130',
            hair: 'Black',
            offense: 'Dishonor',
            dow: '01012016',
            license: 'Abc123!@#',
            dlState: 'CA',
            dlDate: '12312018',
            licPlate: 'China15',
            licState: 'UT',
            licDate: '12252018',
        },
        {
            wid: '12345678901',
            header: 'We Must Save Ch1n@',
            mke: 'Mk#',
            oai:  '123456789',
            name: 'Fa Mulan',
            sex: 'F',             
            race: 'A',        
            height: '504',
            weight: '130',
            hair: 'Black',
            offense: 'Dishonor',
            dow: '01012016',
            license: 'Abc123!@#',
            dlState: 'CA',
            dlDate: '12312018',
            licPlate: 'China15',
            licState: 'UT',
            licDate: '12252018',
        },
        {
            wid: 'Abcdefghij',
            header: 'We Must Save Ch1n@',
            mke: 'Mk#',
            oai:  '123456789',
            name: 'Fa Mulan',
            sex: 'F',            
            race: 'A',       
            height: '504',
            weight: '130',
            hair: 'Black',
            offense: 'Dishonor',
            dow: '01012016',
            license: 'Abc123!@#',
            dlState: 'CA',
            dlDate: '12312018',
            licPlate: 'China15',
            licState: 'UT',
            licDate: '12252018',
        },
        {
            wid: '!@#$%^&*()',
            header: 'We Must Save Ch1n@',
            mke: 'Mk#',
            oai:  '123456789',
            name: 'Fa Mulan',
            sex: 'F',        
            race: 'A',         
            height: '504',
            weight: '130',
            hair: 'Black',
            offense: 'Dishonor',
            dow: '01012016',
            license: 'Abc123!@#',
            dlState: 'CA',
            dlDate: '12312018',
            licPlate: 'China15',
            licState: 'UT',
            licDate: '12252018',
        },
    ],

}

// All fields valid (incl opt), try each drop down item


// future date warrants